version: '3.9'

services:
  db:
    command: 
      - "postgres"
      - "-c"
      - "max_connections=2000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=262kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:13.5-alpine3.14
    networks:
      - db-net
    ports:
      - "5432:5432"

  db-gui:
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - db-net
    ports:
      - "5433:80"

  entrypoint:
    build: ./entrypoint
    environment:
      - ADMIN_PANEL_LISTEN_PORT=8080
      - API_PORT=5555
      - XMPP_LISTEN_PORT=5222
    image: 127.0.0.1:5000/cs-entrypoint
    networks:
      - entrypoint-net
      - external-benchmark-net
      - external-sre-cs-net
    ports:
      - "5222:5222"
      - "5555:5555"
      - "8080:8080"

  xmpp-server:
    build: ./xmpp-server
    environment:
      - ADMIN_JID=admin@cs_entrypoint
      - ADMIN_PASSWORD=admin
      - DB_HOST=db
      - DB_NAME=tigasedb
      - DB_TYPE=postgresql
      - DB_USER_NAME=admin
      - DB_USER_PASSWORD=admin
      - DB_POOL_SIZE=20
      - DB_ROOT_USER_NAME=postgres
      - DB_ROOT_USER_PASSWORD=postgres
      - DEFAULT_VIRTUAL_HOST=cs_entrypoint
      - ENTRYPOINT_REGISTRATION_ADDRESS=entrypoint:5555
      - ENTRYPOINT_REGISTRATION_BACKEND_ADMIN_PANEL_NAME=admin_panel
      - ENTRYPOINT_REGISTRATION_BACKEND_ADMIN_PANEL_PORT=8080
      - ENTRYPOINT_REGISTRATION_BACKEND_XMPP_NAME=xmpp
      - ENTRYPOINT_REGISTRATION_BACKEND_XMPP_PORT=5222
      - ENTRYPOINT_REGISTRATION_MAX_RETRIES=100
      - ENTRYPOINT_REGISTRATION_USER_NAME=admin
      - ENTRYPOINT_REGISTRATION_USER_PASSWORD=admin
      - WAIT_FOR_DB_ADDRESS=db:5432
      - WAIT_FOR_ENTRYPOINT_ADDRESS=entrypoint:5555
    image: 127.0.0.1:5000/cs-xmpp-server
    networks:
      - db-net
      - entrypoint-net

networks:
  db-net:
  entrypoint-net:
  external-benchmark-net:
    external: true
    name: cs-benchmark
  external-sre-cs-net:
    external: true
    name: sre-cs
