version: '3.9'

services:
  db:
    command: 
      - "postgres"
      - "-c"
      - "max_connections=2000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=262kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose: 
      - 5432
    image: postgres:13.5-alpine3.14
    networks:
      - db-network
    restart: always

  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    expose: 
      - 5222
      - 5555
    networks:
      - load-balancer-network
    ports:
      - "5222:5222"
      - "5555:5555"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - db-network
    ports:
      - "5433:80"
    restart: "no"

  tsung-benchmark:
    build: ./tsung-benchmark
    container_name: tsung-benchmark
    networks:
      - load-balancer-network
    ports:
      - "3000:8091"
    restart: "no"
    
  xmpp-server:
    build: ./xmpp-server
    expose:
      - 5222
      - 5277
    image: xmpp-server
    networks:
      - db-network
      - load-balancer-network
    restart: always

networks:
  db-network:
  load-balancer-network:
