version: '3.9'

services:
  db:
    command: 
      - "postgres"
      - "-c"
      - "max_connections=2000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=262kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:13.5-alpine3.14
    networks:
      - db-network

  load-balancer:
    image: madpeh/load-balancer-docker-swarm
    networks:
      - load-balancer-network
    ports:
      - "5222:5222"
      - "5555:5555"

  # pgadmin:
  #   # container_name: pgadmin
  #   image: dpage/pgadmin4:6.2
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   networks:
  #     - db-network
  #   ports:
  #     - "5433:80"
  #   # restart: "no"

  # tsung-benchmark:
  #   # build: ./tsung-benchmark
  #   # container_name: tsung-benchmark
  #   image: madpeh/tsung-benchmark-docker-swarm
  #   networks:
  #     - load-balancer-network
  #   ports:
  #     - "3000:8091"
  #   # restart: "no"
    
  xmpp-server:
    image: madpeh/xmpp-server-docker-swarm
    networks:
      - db-network
      - load-balancer-network
    ports:
      - "8080:8080"

networks:
  db-network:
  load-balancer-network:
