version: '3.9'

services:
  db:
    command: 
      - "postgres"
      - "-c"
      - "max_connections=2000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=262kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
        reservations:
          cpus: "1"
          memory: "512M"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:13.5-alpine3.14
    networks:
      - db-network

  load-balancer:
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: "4"
          memory: "1G"
        reservations:
          cpus: "2"
          memory: "256M"
    image: madpeh/load-balancer-docker-swarm
    networks:
      - load-balancer-network
    ports:
      - "5222:5222"
      - "8080:8080"
    volumes:
      - load-balancer-data:/usr/local/etc/haproxy

  xmpp-server:
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: "8G"
        reservations:
          cpus: "8"
          memory: "8G"
    image: madpeh/xmpp-server-docker-swarm
    networks:
      - db-network
      - load-balancer-network

networks:
  db-network:
  load-balancer-network:

volumes:
  load-balancer-data:
