version: '3.9'

services: 
  load-balancer:
    container_name: load-balancer
    expose: 
      - 5222
    image: haproxy:2.4.8-alpine3.14
    ports:
      - "5222:5222"
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
